name: build
on:
  push:
    branches:
      - master
jobs:
  first_job:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Start
        uses: actions/checkout@master
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build